#!/bin/bash
#git checkout master
#git pull
apt-get install python3-pip
cd dashboard/ 
python3 -m pip install --requirement requirements.txt
python3 dashboard_deltatimes.py html 
mv dashboard_deltatimes.html ../index.html
